In [ ]:
import numpy as np
import pandas as pd
import os
import warnings
import seaborn as sns
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

path=("/content/drive/MyDrive/Project_python_2")

Mounted at /content/drive


In [ ]:
payment_report=pd.read_csv(path + "/payment_report.csv",encoding='utf-8')
product=pd.read_csv(path + "/product.csv",encoding='utf-8')
transactions=pd.read_csv(path + "/transactions.csv",encoding='utf-8')


In [ ]:
payment_report

report_month payment_group  product_id  source_id       volume
0        2023-01       payment          12         45    624110375
1        2023-01       payment          17         45    335715113
2        2023-01       payment          18         45    737784466
3        2023-01       payment          19         45    120963069
4        2023-01       payment          20         45    319653158
..           ...           ...         ...        ...          ...
914      2023-04       payment       15067         45      1504000
915      2023-04        refund        1976         37   3542271587
916      2023-04        refund        1976         38  13831708189
917      2023-04        refund        1976         39   1905435543
918      2023-04        refund        1976         39   3679922071

[919 rows x 5 columns]

In [ ]:
product

product_id category team_own
0            17  PXXXXXB      ASD
1            18  PXXXXXB      ASD
2            20  PXXXXXB      ASD
3           287  PXXXXXB      ASD
4           372  PXXXXXB      ASD
..          ...      ...      ...
487         321  PXXXXXV      ASD
488         322  PXXXXXV      ASD
489         341  PXXXXXV      ASD
490         342  PXXXXXV      ASD
491         367  PXXXXXV      ASD

[492 rows x 3 columns]

In [ ]:
transactions

transaction_id  merchant_id   volume  transType  transStatus  \
0            3002692434            5   100000         24            1   
1            3002692437          305    20000          2            1   
2            3001960110         7255    48605         22            1   
3            3002680710         2270  1500000          2            1   
4            3002680713         2275    90000          2            1   
...                 ...          ...      ...        ...          ...   
1323997      3003723030          305    20000          2            1   
1323998      3003723033         2270   100000          2            1   
1323999      3003723036         2270   100000          2            1   
1324000      3003723039            5      400         22            1   
1324001      3003602967         2250        1          8            1   

          sender_id  receiver_id extra_info      timeStamp  
0        10199794.0     199794.0        NaN  1682932054455  
1        14022211.0   14022211.0        NaN  1682932054912  
2               NaN   10530940.0        NaN  1682932055000  
3        10059206.0      59206.0        NaN  1682932055622  
4        10004711.0       4711.0        NaN  1682932056197  
...             ...          ...        ...            ...  
1323997  24524311.0          NaN        NaN  1683035672634  
1323998  10277242.0     277242.0        NaN  1683035672876  
1323999  10144599.0     144599.0        NaN  1683035672892  
1324000  10028007.0   21013762.0        NaN  1683035672896  
1324001  38559843.0   24501638.0        NaN  1683035673053  

[1324002 rows x 9 columns]

**Part I: EDA**
EDA task

**Df_payment_enriched**

In [ ]:
Df_payment_enriched= payment_report.merge(product,on='product_id',how='left')


In [ ]:
Df_payment_enriched.isna().any()

report_month     False
payment_group    False
product_id       False
source_id        False
volume           False
category          True
team_own          True
dtype: bool

In [ ]:
Df_payment_enriched.dtypes

report_month     object
payment_group    object
product_id        int64
source_id         int64
volume            int64
category         object
team_own         object
dtype: object

In [ ]:
Df_payment_enriched.dropna(inplace=True)
Df_payment_enriched.isnull().sum()

report_month     0
payment_group    0
product_id       0
source_id        0
volume           0
category         0
team_own         0
dtype: int64

In [ ]:
Df_payment_enriched.describe()

product_id  source_id        volume
count    897.000000      897.0  8.970000e+02
mean    1139.573021       45.0  1.338153e+08
std     1161.547355        0.0  4.614672e+08
min       12.000000       45.0  1.000000e+04
25%      634.000000       45.0  1.258000e+06
50%     1023.000000       45.0  7.469786e+06
75%     1578.000000       45.0  4.770741e+07
max    15067.000000       45.0  4.926051e+09

In [ ]:
Df_payment_enriched

report_month payment_group  product_id  source_id     volume  category  \
0        2023-01       payment          12         45  624110375   PXXXXXT   
1        2023-01       payment          17         45  335715113   PXXXXXB   
2        2023-01       payment          18         45  737784466   PXXXXXB   
3        2023-01       payment          19         45  120963069  PXXXXXM2   
4        2023-01       payment          20         45  319653158   PXXXXXB   
..           ...           ...         ...        ...        ...       ...   
909      2023-04       payment        2408         45   10547550   PXXXXXF   
910      2023-04       payment        2419         45     430000   PXXXXXE   
911      2023-04       payment        2587         45     439999   PXXXXXF   
913      2023-04       payment       10039         45    7872489   PXXXXXF   
914      2023-04       payment       15067         45    1504000   PXXXXXR   

    team_own  
0        ASD  
1        ASD  
2        ASD  
3        ASD  
4        ASD  
..       ...  
909      ASL  
910      APS  
911      ASL  
913      ASL  
914      ASL  

[897 rows x 7 columns]

**Df_transactions**

In [ ]:
Df_transactions= transactions


In [ ]:
Df_transactions.drop('extra_info',axis=1,inplace=True)
Df_transactions

transaction_id  merchant_id   volume  transType  transStatus  \
0            3002692434            5   100000         24            1   
1            3002692437          305    20000          2            1   
2            3001960110         7255    48605         22            1   
3            3002680710         2270  1500000          2            1   
4            3002680713         2275    90000          2            1   
...                 ...          ...      ...        ...          ...   
1323997      3003723030          305    20000          2            1   
1323998      3003723033         2270   100000          2            1   
1323999      3003723036         2270   100000          2            1   
1324000      3003723039            5      400         22            1   
1324001      3003602967         2250        1          8            1   

          sender_id  receiver_id      timeStamp  
0        10199794.0     199794.0  1682932054455  
1        14022211.0   14022211.0  1682932054912  
2               NaN   10530940.0  1682932055000  
3        10059206.0      59206.0  1682932055622  
4        10004711.0       4711.0  1682932056197  
...             ...          ...            ...  
1323997  24524311.0          NaN  1683035672634  
1323998  10277242.0     277242.0  1683035672876  
1323999  10144599.0     144599.0  1683035672892  
1324000  10028007.0   21013762.0  1683035672896  
1324001  38559843.0   24501638.0  1683035673053  

[1324002 rows x 8 columns]

In [ ]:
Df_transactions.dropna(inplace=True)
Df_transactions.isnull().sum()

transaction_id    0
merchant_id       0
volume            0
transType         0
transStatus       0
sender_id         0
receiver_id       0
timeStamp         0
dtype: int64

In [ ]:
Df_transactions['sender_id'] = Df_transactions['sender_id'].astype(int)
Df_transactions['receiver_id'] = Df_transactions['receiver_id'].astype(int)
Df_transactions.dtypes

transaction_id    int64
merchant_id       int64
volume            int64
transType         int64
transStatus       int64
sender_id         int64
receiver_id       int64
timeStamp         int64
dtype: object

In [ ]:
Df_transactions.describe()

transaction_id   merchant_id        volume     transType   transStatus  \
count    1.112735e+06  1.112735e+06  1.112735e+06  1.112735e+06  1.112735e+06   
mean     3.002240e+09  1.912325e+03  1.964688e+05  6.937952e+00 -1.229203e+01   
std      1.132099e+07  1.680510e+03  8.366192e+05  6.975682e+00  5.604945e+01   
min      3.000000e+09  5.000000e+00  1.000000e+00  2.000000e+00 -1.333000e+03   
25%      3.001109e+09  3.050000e+02  5.000000e+03  2.000000e+00  1.000000e+00   
50%      3.002203e+09  2.250000e+03  2.000000e+04  2.000000e+00  1.000000e+00   
75%      3.003270e+09  2.270000e+03  1.000000e+05  8.000000e+00  1.000000e+00   
max      6.000066e+09  1.599300e+05  7.869148e+07  2.400000e+01  1.000000e+00   

          sender_id   receiver_id     timeStamp  
count  1.112735e+06  1.112735e+06  1.112735e+06  
mean   9.880451e+07  1.877333e+08  1.683130e+12  
std    6.054279e+08  8.782331e+08  1.708135e+08  
min    1.000001e+07 -6.300000e+01  1.682874e+12  
25%    1.005614e+07  1.564500e+05  1.682993e+12  
50%    1.159814e+07  7.028147e+06  1.683096e+12  
75%    2.103226e+07  3.151356e+07  1.683269e+12  
max    6.993439e+09  2.100000e+10  1.683479e+12

In [ ]:
Df_transactions.head(10)

transaction_id  merchant_id   volume  transType  transStatus  sender_id  \
0       3002692434            5   100000         24            1   10199794   
1       3002692437          305    20000          2            1   14022211   
3       3002680710         2270  1500000          2            1   10059206   
4       3002680713         2275    90000          2            1   10004711   
5       3002680716         2270   200000          2            1   10162232   
6       3002680719           60   200000          2            1   10093450   
9       3002680728         2250    23600          8            1   35074809   
10      3002680731         2270    95000          2            1   10747908   
12      3002680734         6145    10800          8            1   35003241   
13      3002680737            5      700         22            1   38500014   

    receiver_id      timeStamp  
0        199794  1682932054455  
1      14022211  1682932054912  
3         59206  1682932055622  
4          4711  1682932056197  
5        162232  1682932056816  
6         93450  1682932057141  
9        212030  1682932057876  
10       747908  1682932057887  
12       224441  1682932058312  
13       471828  1682932058483

**Part2:Data Wrangling**

1.Top 3 produc_ids highest volume

In [ ]:
max_volume=Df_payment_enriched.groupby('product_id')['volume'].sum().sort_values(ascending=False)
max_volume.head(3)

product_id
429    14667676567
372    13713658515
431     7821984747
Name: volume, dtype: int64

2.Are there any abnormal products against rule:1 product_id is only owed by 1 team


In [ ]:
def check_abnormal_products(df):
    abnormal_products = []
    unique_products = df['product_id'].unique()

    for i in unique_products:
        teams = df[df['product_id'] == i]['team_own'].unique()
        if len(teams) != 1:
            abnormal_products.append(i)

    if abnormal_products:
        return "Abnormal products"
    else:
        return "No abnormal products"

result = check_abnormal_products(Df_payment_enriched)
print(result)



No abnormal products


3.Find the team has had the lowest performance since Q2.2023. Find the category that contributes the least to that team.


In [ ]:
def find_weakest_team(df):

    df_q2 = df[df['report_month'] >= '2023-04']

    team_volume = df_q2.groupby('team_own')['volume'].sum()
    weakest_team = team_volume.idxmin()

    team_data = df_q2[df_q2['team_own'] == weakest_team]
    category_volume = team_data.groupby('category')['volume'].sum()
    weakest_cat = category_volume.idxmin()
    cat_data = team_data[team_data['category'] == weakest_cat]

    print("Team has had the lowest performance: " + str(weakest_team))
    print("Category that contributes the least: " + str(weakest_cat))

    return weakest_team, weakest_cat

weakest_team, weakest_cat = find_weakest_team(Df_payment_enriched)


Team has had the lowest performance: APS
Category that contributes the least: PXXXXXE


4.Find the contribution of source_ids of refund transactions what is the
source_id with the highest contribution?

In [ ]:
def find_refund_source_id(df):
    refund_transactions = df[df['payment_group']== 'refund']
    source_volume = refund_transactions.groupby('source_id')['volume'].sum()
    max_source_id = source_volume.idxmax()
    highest_contribution = source_volume.max()
    print("Source_id with the highest contribution: " + str(max_source_id))
    print("Highest contribution: " + str(highest_contribution))
    return max_source_id, highest_contribution
result=find_refund_source_id(payment_report)

Source_id with the highest contribution: 38
Highest contribution: 36527454759


5.Define type of transactions (‘transaction_type’) for each row, given:
- transType = 2 & merchant_id = 1205: Bank Transfer Transaction
- transType = 2 & merchant_id = 2260: Withdraw Money Transaction
- transType = 2 & merchant_id = 2270: Top Up Money Transaction
- transType = 2 & others merchant_id: Payment Transaction
- transType = 8, merchant_id = 2250: Transfer Money Transaction
- transType = 8 & others merchant_id: Split Bill Transaction
- Remained cases are invalid transactions


In [ ]:
def define_transaction_type(row):
    if row['transType'] == 2:
        if row['merchant_id'] == 1205:
            return 'Bank Transfer Transaction'
        elif row['merchant_id'] == 2270:
            return 'Withdraw Money Transaction'
        else:
            return 'Payment Transaction'
    elif row['transType'] == 8:
        if row['merchant_id'] == 2250:
            return 'Transfer Money Transaction'
        else:
            return 'Split Bill Transaction'
    else:
        return 'Invalid Transaction'

Df_transactions['transaction_type'] = Df_transactions.apply(define_transaction_type, axis=1)
Df_transactions.head()




transaction_id  merchant_id   volume  transType  transStatus  sender_id  \
0      3002692434            5   100000         24            1   10199794   
1      3002692437          305    20000          2            1   14022211   
3      3002680710         2270  1500000          2            1   10059206   
4      3002680713         2275    90000          2            1   10004711   
5      3002680716         2270   200000          2            1   10162232   

   receiver_id      timeStamp            transaction_type  
0       199794  1682932054455         Invalid Transaction  
1     14022211  1682932054912         Payment Transaction  
3        59206  1682932055622  Withdraw Money Transaction  
4         4711  1682932056197         Payment Transaction  
5       162232  1682932056816  Withdraw Money Transaction

6.Of each transaction type (excluding invalid transactions): find the number of transactions, volume, senders and receivers.


In [ ]:
def transaction_summary(df):
  df_valid=df[df['transaction_type']!='Invalid Transaction']
  transaction_summary=df_valid.groupby('transaction_type').agg(
      num_transactions=('transaction_type','count'),
      volume=('volume','sum'),
      senders=('sender_id','nunique'),
      receivers=('receiver_id','nunique')
      )
  return transaction_summary
transaction_summary(Df_transactions)


num_transactions        volume  senders  receivers
transaction_type                                                              
Bank Transfer Transaction              14004   10061351762     9271       9271
Payment Transaction                   294069   57804243017   113563     124846
Split Bill Transaction                  1376       4901464     1323        572
Transfer Money Transaction            341177   37033171492    39021      34585
Withdraw Money Transaction            290502  108606478829   110409     110409